name: Sample Jenkins Job

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_JOB_PATH: ${{ secrets.JENKINS_JOB_PATH }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "$JENKINS_URL/$JENKINS_JOB_PATH/buildWithParameters?token=$JENKINS_TOKEN" \
          --user "$JENKINS_USER:$JENKINS_API_TOKEN"
